staff:
  - level120
  - ChoiKangM
  - zihyeon08
  - parkjihyoun
  - jabin00123
  - JinVibe
group1:
  - yeongwonn01
  - EOH0
  - JungHJ02
group2:
  - Juuuujuu
  - ktykty0525
  - oje2024
  - youngni05
group3:
  - jinyongu
  - pigmal24
  - taile9
  - hanmj34
group4:
  - rlamrkdals
  - juahong24
  - Yujin-J
  - ruminantchloe
group5:
  - YoonKeumJae
  - ahapwhs0414
  - SangYoupLee
group6:
  - seokmin0719
  - o-heat
group7:
  - joshmoon827
  - Min-beom
  - jgsajw
group8:
  - mings0o0ng
  - ovleluv
  - neverx3gu
group9:
  - taekhyunv
  - ywkm1n
  - sh4663
